### ISSUE TITLE
Installation error - rjsmin1.1.0

### ISSUE THREAD

**Issue by anelda** [MOH-Zambia/MFL#3]
Hi @csiwale,

Thanks for making this tool available! I am looking at MFLs across Africa as part of a research project (http://afrimapr.org) and came across this repository.

I followed your installation instructions but got an error message:

`ERROR: django-compressor 2.2 has requirement rjsmin==1.0.12, but you'll have rjsmin 1.1.0 which is incompatible.`

Then edited the `requirements.txt` to download rjsmin 1.0.12 instead. 

The installation ran to completion successfully, but when I run `python manage.py runserver` there is another error and I'm stuck as my django debug skills are very limited.

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/talarify/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/talarify/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/talarify/Desktop/MFL/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/talarify/Desktop/MFL/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/talarify/Desktop/MFL/lib/python3.6/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/talarify/Desktop/MFL/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/talarify/Desktop/MFL/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/talarify/Desktop/MFL/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/talarify/Desktop/MFL/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/talarify/Desktop/MFL/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/talarify/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/talarify/Desktop/MFL/lib/python3.6/site-packages/leaflet/__init__.py", line 21, in <module>
    from django.contrib.staticfiles.templatetags.staticfiles import static
ModuleNotFoundError: No module named 'django.contrib.staticfiles.templatetags'
```
I run Ubuntu 18.04.4.

Can you please help?

thanks!

**Comment by csiwale** [comment]
Hi

I am updating the installation instructions on Github, will let you know by end of day today

**Comment by anelda** [comment]
Hi @csiwale, thanks for your speedy feedback! I was mostly looking for the data and found it in https://github.com/MOH-Zambia/MFL/tree/master/geography/data.

Under what license does the Ministry make the data available? I see there is a license file in your repository but that is for the code. Do you also have a data license e.g. https://opendatacommons.org/licenses/odbl/index.html?

I am working with colleagues from http://afrimapr.org, healthsites.io and others to understand MFL availability in Africa. So glad I came across your repo. This is great work!
